xd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: xd_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: #由于隐私问题，不展示
    access-key-secret: #由于隐私问题，不展示
    bucket-name: sky-take-out-iamzwxyy
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: #由于隐私问题，不展示
    secret: #由于隐私问题，不展示