xd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: xd_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEqs9JQhXHfT3W46BYz
    access-key-secret: Vk73Ggp098Kw9NqT9qvfKBhUr7VtGR
    bucket-name: sky-take-out-iamzwxyy
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx11617ccaf8f07796
    secret: 787ba64584287ffc7dadb5943686000d